### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Reponedor** [leosamu/pythonMoocProblems#1]
I'm doing the exercises of the repository. How could send you them to you ?. Thanks for all . ( i wanted send you a message. How i didn't find this option, i think that create an issue was a nice option. Apologize me for it if has been a error )

**Comment by leosamu** [comment]
Woa mate, i made a python course on edx.org and linked them there.

https://www.edx.org/es/course/python-aprender-a-programar

The original idea was to instead of a code get a message but since i needed a way to link the answers to the platform correction method i used those codes.

See you!
